name: Build R3G Mihomo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: Init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget upx
    - name: Clone
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel && sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build MI-R3G
      env:
        TNAME: MI-R3G
      run: |
        cd /opt/rt-n56u/trunk
        cp configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        for f in SHADOWSOCKS SSSERVER DNSFORWARDER ADBYBY FRPC FRPS ALIDDNS SMARTDNS V2RAY XRAY TROJAN KOOLPROXY CADDY ADGUARDHOME WYY ZEROTIER MENTOHUST SCUTCLIENT TUNSAFE SRELAY; do sed -i "/CONFIG_FIRMWARE_INCLUDE_$f/d" .config; done
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DROPBEAR=y" >> .config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv images/*.trx /opt/images/
    - name: Add mihomo
      run: |
        curl -kL -o /tmp/mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.19.31/mihomo-linux-mipsle-softfloat-v1.19.31.gz
        gunzip /tmp/mihomo.gz
        upx --best /tmp/mihomo -o /opt/images/mihomo || cp /tmp/mihomo /opt/images/mihomo
        ls -la /opt/images/
    - name: Upload
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-R3G-Mihomo
        path: /opt/images
